#!/usr/bin/env python3
# from typing import *

FIRST = 'Alice'
SECOND = 'Bob'

# def solve(T: str) -> Tuple[str, str, str, str, str]:
def solve(T):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = input()
    a, b, c, d, e = solve(T)
    print(a)
    print(b)
    print(c)
    print(d)
    print(e)

if __name__ == '__main__':
    main()
