#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(D: int, T: int, S: int) -> str:
def solve(D, T, S):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    D, T, S = map(int, input().split())
    a = solve(D, T, S)
    print(a)

if __name__ == '__main__':
    main()
