#!/usr/bin/env python3
# from typing import *



# def solve(H: int) -> int:
def solve(H):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H = int(input())
    a = solve(H)
    print(a)

if __name__ == '__main__':
    main()
