#!/usr/bin/env python3
# from typing import *



# def solve(P: int) -> int:
def solve(P):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    P = int(input())
    a = solve(P)
    print(a)

if __name__ == '__main__':
    main()
